# Generated by Django 4.1.1 on 2022-10-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'User with this email already exists!'}, max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
